// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_uN68iJEtIpMc2mv6xst5ttxlgnnFh4',
    appId: '1:789779071696:web:fbef86a7173df44d0014d5',
    messagingSenderId: '789779071696',
    projectId: 'targetapp-2af6f',
    authDomain: 'targetapp-2af6f.firebaseapp.com',
    storageBucket: 'targetapp-2af6f.appspot.com',
    measurementId: 'G-WMX4ZWY7KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAch1rZiGcxhbJ4pdS6XuTM3e_cbytzOHw',
    appId: '1:789779071696:android:5b917d7da5ef07d50014d5',
    messagingSenderId: '789779071696',
    projectId: 'targetapp-2af6f',
    storageBucket: 'targetapp-2af6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_YW3WbhUgEwNC9bIsGASOyz4av4xKk4',
    appId: '1:789779071696:ios:659e5652f4b432220014d5',
    messagingSenderId: '789779071696',
    projectId: 'targetapp-2af6f',
    storageBucket: 'targetapp-2af6f.appspot.com',
    iosBundleId: 'com.example.targetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA_YW3WbhUgEwNC9bIsGASOyz4av4xKk4',
    appId: '1:789779071696:ios:2944d2044631097e0014d5',
    messagingSenderId: '789779071696',
    projectId: 'targetapp-2af6f',
    storageBucket: 'targetapp-2af6f.appspot.com',
    iosBundleId: 'com.example.targetApp.RunnerTests',
  );
}
